.

diff --git a/commands/host/cloudflare b/commands/host/cloudflare
--- a/commands/host/cloudflare
+++ b/commands/host/cloudflare
@@ -272,29 +272,44 @@ install_cloudflared() {
 install_flarectl() {
     flarectl_version=$(~/.ddev/bin/flarectl -version 2>/dev/null)
     if [ $? -ne 0 ]; then
-        echo "flarectl is not installed"
+        echo "
+flarectl is not installed"
         extracted_version=""
     else
         extracted_version=$(echo "$flarectl_version" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
-        echo "Current flarectl version: $extracted_version"
+        echo "
+Current flarectl version: $extracted_version"
     fi
-
-    latest_release_info=$(curl -s "https://api.github.com/repos/cloudflare/cloudflare-go/releases/latest")
     
+    # Get the latest release information from the GitHub API
+    echo "
+Checking for the latest flarectl version..."
+
+    # sometimes I have dns issues with Github that causes this to fail
+    
+    latest_release_info=$(curl -s "https://api.github.com/repos/cloudflare/cloudflare-go/releases/latest")
+    if [ $? -ne 0 ]; then
+        echo "Request for flarectl release info failed. Please try again later."
+        return
+    fi
+        
     # Extract the tag name from the latest release information
     latest_tag=$(echo "$latest_release_info" | jq -r '.tag_name')
     
     formatted_tag=${latest_tag#v}
-    echo "Latest flarectl version: $latest_tag"
+    echo "
+Latest flarectl version: $latest_tag"
     if [[ "$extracted_version" == "$formatted_tag" ]]; then
-        echo "flarectl is already up to date"
+        echo "
+flarectl is already up to date"
         return
     fi
 
     # Construct the download URL using the latest tag
     download_url="https://github.com/cloudflare/cloudflare-go/releases/download/${latest_tag}/flarectl_${formatted_tag}_${OS}_${ARCH}.tar.gz"
 
-    echo "Downloading flarectl ${latest_tag} for ${OS}_${ARCH}... from $download_url"
+    echo "
+Downloading flarectl ${latest_tag} for ${OS}_${ARCH}... from $download_url"
 
     # Download the .tar.gz file to a temporary location
     curl -L "$download_url" -o /tmp/flarectl.tar.gz
@@ -311,6 +326,9 @@ install_flarectl() {
 
     #curl -L $download_url | tar -xz -C ~/.ddev/bin
     sudo chmod +x ~/.ddev/bin/flarectl
+    
+    echo "
+flarectl ${latest_tag} has been installed"
 }
 
 install() {
